### ISSUE TITLE
wine-gallium-nine fc25

### ISSUE THREAD

**Issue by smekras** [dyskette/packages#1]
I tried installing the latest (2.0.2) build of your wine-gallium-nine on fedora 25, but dnf gives me this message:

> Error: nothing provides wine-capi(x86-32) = 2.0-2.with_nine.fc25 needed by wine-2.0-2.with_nine.fc25.x86_64

**Comment by dyskette** [comment]
Did you create the `.repo` file as shown in the installation intsructions?

**Comment by smekras** [comment]
Pretty sure I did, but will have to check once I get my PC working again. Will get back to you on that. Hopefully I forgot to save it or something.

**Comment by smekras** [comment]
Turns out I saved the repo file in the wrong folder. Installed just fine now.

**Comment by lifeofdan** [comment]
I ran into this exact error. It is quite misleading that the "Quick enable" for the copr repo makes this error happen. I am glad someone wrote a bug report for it. Solved my issue as well. Thanks!
