### ISSUE TITLE
wine-gallium-nine for f27?

### ISSUE THREAD

**Issue by smekras** [dyskette/packages#4]
Are there plans for it? Any ETA? Something we can do to help?

...or it is already out there and I'm just being an idiot who can't find it? (always a possibility)

**Comment by dyskette** [comment]
Sorry.

That's all I can say for this long time of nothingness. Life has kept me busy and I've been learning and doing a lot of stuff, enough to not even bother with the usual packaging I do on the sideline.

There is a new package built right now of wine 3.6. And for the record, I keep the sources and diff files in https://dyskette.fedorapeople.org/wine/ if someone wants to keep building it more steadily than me.
