### ISSUE TITLE
Missing dependency - Fedora 28

### ISSUE THREAD

**Issue by smekras** [dyskette/packages#5]
I tried installing the latest version but I have hit a snag with one of the needed packages. Specifically:

`nothing provides wine-capi(x86-32) = 3.6-2.with_nine.fc28 needed by wine-3.6-2.with_nine.fc28.x86_64`

the x86_64 version of wine-capi is there, so I am guessing the x86-32 one slipped through the cracks. 
Please look at it at your convenience, and good to see you're still around.

On a sidenote, dnf also gave me this message for a few other dependencies, but I was able to manually install them:
"/usr/bin/ntlm_auth" - solved by installing samba-winbind-clients from updates repo
"mesa-dri-drivers(x86-32)" - solved by installing mesa-dri-drivers.i686 from updates repo
"mingw32-wine-gecko = 2.47" - solved by installing mingw32-wine-gecko from fedora repo
"mingw64-wine-gecko = 2.47" - solved by installing mingw64-wine-gecko from fedora repo

**Comment by dyskette** [comment]
Weird. I cannot reproduce... I'm installing wine gallium from COPR in a clean installation right now.

So, can you still reproduce it? Are you sure both 32 and 64 bits are enabled as [the instructions ](https://copr.fedorainfracloud.org/coprs/dyskette/wine-gallium-nine/).

**Comment by smekras** [comment]
Unfortunately, yes.
I hoped this was a case of me being my usual scatterbrained self, but the moment I try to install the version of wine from your repo, I his the wine-capi wall.

**Comment by dyskette** [comment]
OK, I'm short of time right now because of my job, but I will try to check it out in the weekend (if I have it free for myself).

It would be lovely if you could install it in a fresh Fedora 28 or if you have a virtual machine where could try it. But if not, I'll do it.

**Comment by smekras** [comment]
It was a clean f28 installation, and I don't believe I had the chance to install anything that would interfere prior to trying this. That said, I cannot be 100% certain.

Regardless... tackle this at your convenience, and thanks for bothering in the first place.

**Comment by smekras** [comment]
Update to the above, different PC, still a clean F28 installation
First, it gave me this: 
Problem: conflicting requests
  - nothing provides wine-mono = 4.7.1 needed by wine-3.6-2.with_nine.fc28.i686
  - nothing provides wine-mono = 4.7.1 needed by wine-3.6-2.with_nine.fc28.x86_64

Then, after installing wine-mono (4.7.1-2.fc28) from fedora repo, I got this:
Problem: conflicting requests
  - package wine-3.6-2.with_nine.fc28.i686 requires wine-twain(x86-32) = 3.6-2.with_nine.fc28, but none of the providers can be installed
  - package wine-3.6-2.with_nine.fc28.x86_64 requires wine-core(x86-64) = 3.6-2.with_nine.fc28, but none of the providers can be installed
  - nothing provides sane-backends-libs(x86-32) needed by wine-twain-3.6-2.with_nine.fc28.i686
  - nothing provides mesa-libd3d(x86-64) needed by wine-core-3.6-2.with_nine.fc28.x86_64
