### ISSUE TITLE
Fedora 29 on COPR repository

### ISSUE THREAD

**Issue by RixzZ** [dyskette/packages#6]
Hello.

The COPR repository for Trackma doesn't have data for Fedora 29 which makes it incompatible with it. Can you add support for it?

**Comment by dyskette** [comment]
Hi. Yes, of course, I'll get to it in the weekend.

**Comment by RixzZ** [comment]
That's great to hear.

Thanks a lot :)

**Comment by dyskette** [comment]
It's done. Also updated to the newest version. I tested the gtk front on my PC and it seems to be working.

**Comment by RixzZ** [comment]
I can confirm it's working perfectly on my side. I had to re-auth AniList because it seems the API version changed, but after that works like before the update.

Thanks for updating it so quickly!

**Comment by dyskette** [comment]
No problem.
